// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sanpgbcugypynzreujrx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNhbnBnYmN1Z3lweW56cmV1anJ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzNzMwODUsImV4cCI6MjA2MTk0OTA4NX0.e12MFnIyJ2KF-3WWaIMKg89_dirulJWz-nrlUUwIWi8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);